### ISSUE TITLE
It keeps running but it doesnt create csv file

### ISSUE THREAD

**Issue by rickkk856** [SwatiModi/pinterest-web-scraper#2]
Teleport Successful!
99
99
6
30
26
16
7
7

and keeps loading number infinitely... 

I tried to change  pin data to a small number to get to the next step but it did not workout

    if len(pin_data) > 300:
        break

**Comment by rickkk856** [comment]
it might be a problem on loop... i guess it's because pin_data doesn't append to a list, so it needs do get many files to generate the CSV

**Comment by SwatiModi** [comment]
Hi @rickkk856, 

You were right about the the append issue, thank you reporting it.
Checkout the latest commit, I have resolved the problem.

**Comment by rickkk856** [comment]
I was trying to put an time loop but i'm Very Noob at It lol , even tho i'll try later
